Repository snowio/brightpearl-data-model, pull requests merged in 2023-10, with the labels that each got.

#21 Fix - updating order model and adding sales order model
  src/Api/ModelInterface.php
  src/Order.php
  src/Order/Assignment.php
  src/Order/Assignment/Current.php
  src/Order/Currency.php
  src/Order/Delivery.php
  src/Order/Invoice.php
  src/Order/InvoiceCollection.php
  src/Order/Parties.php
  src/Order/Parties/Delivery.php
  src/Order/Status.php
  tests/Unit/Order/OrderTest.php
Labels: work in progress

#19 Feature/model interface
  src/Contact.php
  src/ContactCreate.php
  src/CustomerPayment.php
  src/GoodsOutNote.php
  src/Notification.php
  src/Order.php
  src/OrderResponse.php
  src/PostalAddress.php
  src/Product.php
  src/ProductAvailability.php
  src/SalesCredit.php
  src/SalesOrderResponse.php
  tests/Unit/GoodsOutNote/GoodsOutNoteTest.php
  tests/Unit/OrderResponse/OrderResponseTest.php
  tests/Unit/Product/ProductTest.php
  tests/Unit/ProductAvailability/ProductAvailabilityTest.php
  tests/Unit/SalesCredit/SalesCreditTest.php
  tests/Unit/SalesOrderResponse/SalesOrderResponseTest.php
Labels: work in progress

#23 Feature- Update order response model
  src/OrderResponse/Parties.php
  src/OrderResponse/Parties/Billing.php
  src/OrderResponse/Parties/Delivery.php
  src/OrderResponse/Parties/Supplier.php
Labels: work in progress

#26 Adds missing custom fields array to GetSalesOrder
  src/SalesOrder/GetSalesOrder.php
  tests/Unit/SalesOrder/GetSalesOrderTest.php
  tests/resources/SalesOrder/get-sales-order.json
Labels: passed review

#29 added type check in equals and toJson
  src/ContactCreate.php
  src/ContactCreate/Communication.php
  src/ContactCreate/Communication/Emails.php
  src/GoodsOutNote.php
  src/Order.php
  src/Order/Assignment.php
  src/Order/Parties.php
  src/OrderResponse.php
  src/OrderResponse/Parties.php
  src/OrderResponse/Row.php
  src/Product.php
  src/Product/FinancialDetails.php
  src/Product/SalesChannel.php
  src/Product/Stock.php
  src/ProductAvailability.php
  src/SalesCredit.php
  src/SalesCredit/Delivery.php
  src/SalesOrderResponse.php
  src/SalesOrderResponse/Customer.php
  tests/Unit/Order/PartiesTest.php
Labels: pending review
